[package]
name = "infra"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
chrono = { workspace = true }
domain = { workspace = true }
sea-orm = { workspace = true }
