[package]
name = "domain"
version.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
chrono = { workspace = true }
paste = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
