apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-task-dev
resources:
  - ../../bases

patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
      name: smart-task
  - path: patch-configmap-api-server.yaml
    target:
      kind: ConfigMap
      name: smart-task-api-server
  - path: patch-deployment-api-server.yaml
    target:
      kind: Deployment
      name: smart-task-api-server