apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: smart-task-namespace-dev
resources:
  - ../../bases

patches:
  - path: patch-namespace.yaml
    target:
      kind: Namespace
      name: smart-task-namespace