apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-task-api-server
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: smart-task-api-server
          image: smart-task:latest
